In [286]:
import pandas as pd
train_data = pd.read_csv("renfe.csv")
train_data.head()

,insert_date,origin,destination,start_date,end_date,train_type,price,train_class,fare
0,2019-04-11 21:49:46,MADRID,BARCELONA,2019-04-18 05:50:00,2019-04-18 08:55:00,AVE,68.95,Preferente,Promo
1,2019-04-11 21:49:46,MADRID,BARCELONA,2019-04-18 06:30:00,2019-04-18 09:20:00,AVE,75.40,Turista,Promo
2,2019-04-11 21:49:46,MADRID,BARCELONA,2019-04-18 07:00:00,2019-04-18 09:30:00,AVE,106.75,Turista Plus,Promo
3,2019-04-11 21:49:46,MADRID,BARCELONA,2019-04-18 07:30:00,2019-04-18 10:40:00,AVE,90.50,Turista Plus,Promo
4,2019-04-11 21:49:46,MADRID,BARCELONA,2019-04-18 08:00:00,2019-04-18 10:30:00,AVE,88.95,Turista,Promo

In [287]:
train_data.shape

(7671354, 9)

### 数据去空

In [288]:
train_data.isna().any()

insert_date    False
origin         False
destination    False
start_date     False
end_date       False
train_type     False
price           True
train_class     True
fare            True
dtype: bool

In [289]:
train_data = train_data.dropna()
train_data.shape

(7098233, 9)

In [298]:
train_data["day"] = train_data["start_date"].str[5:10]
train_data["hour"] = train_data["start_date"].str[11:]

### 出行人数最多是哪一天

In [328]:
checi = train_data.groupby("day")["insert_date"].count()
checi.describe()

count      192.000000
mean     36969.963542
std      25046.339741
min        636.000000
25%      15917.750000
50%      27687.500000
75%      57819.750000
max      94087.000000
Name: insert_date, dtype: float64

In [329]:
checi.idxmax()

'05-30'

In [349]:
checi

day
04-12      699
04-13      636
04-14     2663
04-15     5909
04-16     9072
04-17    10168
04-18    11851
04-19    12811
04-20    13133
04-21    18174
04-22    25349
04-23    30720
04-24    33444
04-25    37706
04-26    34737
04-27    26754
04-28    35895
04-29    42972
04-30    44151
05-01    36116
05-02    40706
05-03    46189
05-04    32381
05-05    41503
05-06    53972
05-07    54323
05-08    56512
05-09    60690
05-10    57661
05-11    41371
         ...
09-21     7837
09-22    10387
09-23    11624
09-24    11601
09-25    11893
09-26    12633
09-27    12051
09-28     7812
09-29     9768
09-30    10590
10-01     9872
10-02     9631
10-03     9598
10-04     9194
10-05     6047
10-06     7785
10-07     8974
10-08     9041
10-09     8801
10-10     9599
10-11     9203
10-12     6017
10-13     6993
10-14     6873
10-15     5806
10-16     4982
10-17     4022
10-18     2905
10-19     1209
10-20      717
Name: insert_date, Length: 192, dtype: int64

### 大家去了哪里

In [331]:
train_data.loc[train_data["day"]=="05-30","destination"].value_counts()

MADRID        46417
BARCELONA     17398
VALENCIA      13854
SEVILLA       13664
PONFERRADA     2754
Name: destination, dtype: int64

### 去掉人数 统计班车信息

In [333]:
train_price_wave = train_data.drop("insert_date",axis =1)

In [334]:
train_price_wave.shape

(7098233, 10)

In [340]:
train_price_wave = train_price_wave.drop_duplicates()
train_price_wave.shape

(89515, 10)

### 价格波动分析

In [341]:
train_price_wave["start_date"].max()

'2019-10-20 22:14:00'

In [342]:
train_price_wave["start_date"].min()

'2019-04-12 05:50:00'

In [343]:
train_price_wave_2019 = train_price_wave.loc[(train_price_wave["start_date"]>="2019-04-00")&(train_price_wave["start_date"]<="2019-10-30")]
train_price_wave_2019.shape

(89515, 10)

### 马德里到巴塞罗那的票价波动

In [344]:
M_to_B = train_price_wave_2019.loc[(train_price_wave_2019["origin"]=="MADRID")&(train_price_wave_2019["destination"]=="BARCELONA")]
M_to_B.shape

(17799, 10)

In [345]:
M_to_B

,origin,destination,start_date,end_date,train_type,price,train_class,fare,day,hour
0,MADRID,BARCELONA,2019-04-18 05:50:00,2019-04-18 08:55:00,AVE,68.95,Preferente,Promo,04-18,05:50:00
1,MADRID,BARCELONA,2019-04-18 06:30:00,2019-04-18 09:20:00,AVE,75.40,Turista,Promo,04-18,06:30:00
2,MADRID,BARCELONA,2019-04-18 07:00:00,2019-04-18 09:30:00,AVE,106.75,Turista Plus,Promo,04-18,07:00:00
3,MADRID,BARCELONA,2019-04-18 07:30:00,2019-04-18 10:40:00,AVE,90.50,Turista Plus,Promo,04-18,07:30:00
4,MADRID,BARCELONA,2019-04-18 08:00:00,2019-04-18 10:30:00,AVE,88.95,Turista,Promo,04-18,08:00:00
5,MADRID,BARCELONA,2019-04-18 08:30:00,2019-04-18 11:15:00,AVE,107.70,Turista,Flexible,04-18,08:30:00
6,MADRID,BARCELONA,2019-04-18 09:30:00,2019-04-18 12:34:00,AVE,107.70,Turista,Flexible,04-18,09:30:00
7,MADRID,BARCELONA,2019-04-18 10:30:00,2019-04-18 13:15:00,AVE,102.15,Turista Plus,Promo,04-18,10:30:00
8,MADRID,BARCELONA,2019-04-18 11:30:00,2019-04-18 14:40:00,AVE,102.15,Turista Plus,Promo,04-18,11:30:00
9,MADRID,BARCELONA,2019-04-18 12:30:00,2019-04-18 15:30:00,AVE,107.70,Turista,Flexible,04-18,12:30:00
10,MADRID,BARCELONA,2019-04-18 13:25:00,2019-04-18 16:24:00,AVE-TGV,107.70,Turista,Flexible,04-18,13:25:00
11,MADRID,BARCELONA,2019-04-18 14:00:00,2019-04-18 16:30:00,AVE,100.40,Turista,Promo,04-18,14:00:00
12,MADRID,BARCELONA,2019-04-18 14:30:00,2019-04-18 17:21:00,AVE,107.70,Turista,Flexible,04-18,14:30:00
14,MADRID,BARCELONA,2019-04-18 16:30:00,2019-04-18 19:15:00,AVE,102.15,Turista Plus,Promo,04-18,16:30:00
15,MADRID,BARCELONA,2019-04-18 17:30:00,2019-04-18 20:40:00,AVE,75.40,Turista,Promo,04-18,17:30:00
16,MADRID,BARCELONA,2019-04-18 18:30:00,2019-04-18 21:20:00,AVE,90.50,Turista Plus,Promo,04-18,18:30:00
17,MADRID,BARCELONA,2019-04-18 19:00:00,2019-04-18 21:30:00,AVE,115.65,Preferente,Promo,04-18,19:00:00
18,MADRID,BARCELONA,2019-04-18 19:30:00,2019-04-18 22:40:00,AVE,85.10,Turista,Promo,04-18,19:30:00
19,MADRID,BARCELONA,2019-04-18 20:30:00,2019-04-18 23:40:00,AVE,85.10,Turista,Promo,04-18,20:30:00
21,MADRID,BARCELONA,2019-05-18 06:20:00,2019-05-18 09:29:00,AVE,66.75,Turista,Promo,05-18,06:20:00
22,MADRID,BARCELONA,2019-05-18 07:30:00,2019-05-18 10:40:00,AVE,85.10,Turista,Promo,05-18,07:30:00
23,MADRID,BARCELONA,2019-05-18 08:30:00,2019-05-18 11:15:00,AVE,85.10,Turista,Promo,05-18,08:30:00
24,MADRID,BARCELONA,2019-05-18 09:30:00,2019-05-18 12:34:00,AVE,85.10,Turista,Promo,05-18,09:30:00
25,MADRID,BARCELONA,2019-05-18 10:30:00,2019-05-18 13:15:00,AVE,75.40,Turista,Promo,05-18,10:30:00
26,MADRID,BARCELONA,2019-05-18 11:30:00,2019-05-18 14:40:00,AVE,75.40,Turista,Promo,05-18,11:30:00
27,MADRID,BARCELONA,2019-05-18 12:30:00,2019-05-18 15:30:00,AVE,75.40,Turista,Promo,05-18,12:30:00
28,MADRID,BARCELONA,2019-05-18 13:25:00,2019-05-18 16:24:00,AVE-TGV,75.40,Turista,Promo,05-18,13:25:00
29,MADRID,BARCELONA,2019-05-18 15:30:00,2019-05-18 18:40:00,AVE,86.80,Preferente,Promo,05-18,15:30:00
30,MADRID,BARCELONA,2019-05-18 16:30:00,2019-05-18 19:15:00,AVE,80.15,Turista Plus,Promo,05-18,16:30:00
31,MADRID,BARCELONA,2019-05-18 17:30:00,2019-05-18 20:40:00,AVE,75.40,Turista,Promo,05-18,17:30:00
...,...,...,...,...,...,...,...,...,...,...
7523715,MADRID,BARCELONA,2019-06-03 05:50:00,2019-06-03 08:55:00,AVE,75.39,Turista,Promo,06-03,05:50:00
7523754,MADRID,BARCELONA,2019-05-24 21:25:00,2019-05-24 23:55:00,AVE,143.40,Preferente,Promo,05-24,21:25:00
7531527,MADRID,BARCELONA,2019-05-29 16:30:00,2019-05-29 19:15:00,AVE,127.05,Preferente,Promo,05-29,16:30:00
7531554,MADRID,BARCELONA,2019-05-28 17:00:00,2019-05-28 19:30:00,AVE,94.55,Turista Plus,Promo,05-28,17:00:00
7531730,MADRID,BARCELONA,2019-05-27 06:10:00,2019-05-27 08:40:00,AVE,112.55,Preferente,Promo,05-27,06:10:00
7531731,MADRID,BARCELONA,2019-05-27 11:30:00,2019-05-27 14:40:00,AVE,129.30,Turista Plus,Flexible,05-27,11:30:00
7531744,MADRID,BARCELONA,2019-05-27 20:00:00,2019-05-27 22:30:00,AVE,88.95,Turista,Promo,05-27,20:00:00
7531799,MADRID,BARCELONA,2019-06-20 06:10:00,2019-06-20 08:40:00,AVE,66.77,Turista,Promo,06-20,06:10:00
7532310,MADRID,BARCELONA,2019-05-25 12:30:00,2019-05-25 15:30:00,AVE,110.60,Preferente,Promo,05-25,12:30:00
7532312,MADRID,BARCELONA,2019-05-25 11:30:00,2019-05-25 14:40:00,AVE,129.30,Turista Plus,Flexible,05-25,11:30:00
7533729,MADRID,BARCELONA,2019-05-27 08:00:00,2019-05-27 10:30:00,AVE,169.20,Preferente,Promo,05-27,08:00:00
7533937,MADRID,BARCELONA,2019-05-25 12:30:00,2019-05-25 15:30:00,AVE,129.30,Turista Plus,Flexible,05-25,12:30:00
7542984,MADRID,BARCELONA,2019-05-27 19:00:00,2019-05-27 21:30:00,AVE,152.50,Turista Plus,Flexible,05-27,19:00:00
7543549,MADRID,BARCELONA,2019-05-25 12:30:00,2019-05-25 15:30:00,AVE,140.00,Preferente,Flexible,05-25,12:30:00
7543563,MADRID,BARCELONA,2019-05-24 18:00:00,2019-05-24 20:30:00,AVE,127.10,Turista,Flexible,05-24,18:00:00
7557467,MADRID,BARCELONA,2019-06-07 14:30:00,2019-06-07 17:21:00,AVE,127.05,Preferente,Promo,06-07,14:30:00
7557570,MADRID,BARCELONA,2019-06-03 06:10:00,2019-06-03 08:40:00,AVE,66.77,Turista,Promo,06-03,06:10:00
7557595,MADRID,BARCELONA,2019-05-25 08:30:00,2019-05-25 11:15:00,AVE,140.00,Preferente,Flexible,05-25,08:30:00
7565428,MADRID,BARCELONA,2019-05-27 13:25:00,2019-05-27 16:24:00,AVE-TGV,181.50,Preferente,Flexible,05-27,13:25:00
7584063,MADRID,BARCELONA,2019-05-24 12:30:00,2019-05-24 15:30:00,AVE,140.00,Preferente,Flexible,05-24,12:30:00
7584069,MADRID,BARCELONA,2019-05-24 08:30:00,2019-05-24 11:15:00,AVE,140.00,Preferente,Flexible,05-24,08:30:00
7584071,MADRID,BARCELONA,2019-05-24 17:30:00,2019-05-24 20:40:00,AVE,102.15,Turista Plus,Promo,05-24,17:30:00
7584073,MADRID,BARCELONA,2019-05-24 06:20:00,2019-05-24 09:29:00,AVE,107.70,Turista,Flexible,05-24,06:20:00
7598233,MADRID,BARCELONA,2019-05-25 09:30:00,2019-05-25 12:34:00,AVE,110.60,Preferente,Promo,05-25,09:30:00
7605173,MADRID,BARCELONA,2019-06-03 21:25:00,2019-06-03 23:55:00,AVE,49.15,Turista Plus,Promo,06-03,21:25:00
7605778,MADRID,BARCELONA,2019-07-03 07:30:00,2019-07-03 10:40:00,AVE,75.39,Turista,Promo,07-03,07:30:00
7605792,MADRID,BARCELONA,2019-07-03 11:30:00,2019-07-03 14:40:00,AVE,85.08,Turista,Promo,07-03,11:30:00
7606622,MADRID,BARCELONA,2019-05-25 09:30:00,2019-05-25 12:34:00,AVE,140.00,Preferente,Flexible,05-25,09:30:00
7632157,MADRID,BARCELONA,2019-05-25 15:30:00,2019-05-25 18:40:00,AVE,129.30,Turista Plus,Flexible,05-25,15:30:00
7634141,MADRID,BARCELONA,2019-06-28 15:30:00,2019-06-28 18:40:00,AVE,102.15,Turista Plus,Promo,06-28,15:30:00

In [360]:
M_to_B["train_class"].value_counts()

Turista                9685
Turista Plus           4104
Preferente             3328
TuristaSólo plaza H     682
Name: train_class, dtype: int64

### 我们发现 同一班车每天不同时刻发车的票价 也是不同的。那我们对当天的票价进行一个平均处理。

In [367]:
M_to_B_Turista = M_to_B.loc[M_to_B["train_class"]=="Turista"]
M_to_B_Turista_price = M_to_B_Turista.groupby("day")["price"].mean().round(0)
M_to_B_Turista_price

day
04-12    107.0
04-13    102.0
04-14    105.0
04-15     95.0
04-16     91.0
04-17     97.0
04-18     94.0
04-19     83.0
04-20     91.0
04-21     98.0
04-22    103.0
04-23     97.0
04-24     89.0
04-25     86.0
04-26     88.0
04-27     87.0
04-28     87.0
04-29     89.0
04-30     91.0
05-01     87.0
05-02     75.0
05-03     83.0
05-04     89.0
05-05     95.0
05-06     85.0
05-07     83.0
05-08     85.0
05-09     86.0
05-10     89.0
05-11     89.0
         ...
09-21     77.0
09-22     74.0
09-23     79.0
09-24     83.0
09-25     85.0
09-26     83.0
09-27     81.0
09-28     77.0
09-29     77.0
09-30     79.0
10-01     82.0
10-02     85.0
10-03     84.0
10-04     84.0
10-05     79.0
10-06     80.0
10-07     79.0
10-08     82.0
10-09     85.0
10-10     84.0
10-11     84.0
10-12     79.0
10-13     80.0
10-14     79.0
10-15     82.0
10-16     85.0
10-17     84.0
10-18     84.0
10-19     79.0
10-20     80.0
Name: price, Length: 192, dtype: float64

### 如果想知道哪天哪个时刻票最便宜

In [404]:
M_to_B_Turista_price_min = M_to_B_Turista.groupby("day")["price"].min().round(0)
M_to_B_Turista_price_min =M_to_B_Turista_price_min[M_to_B_Turista_price_min>0]
M_to_B_Turista_price_min

day
04-12    43.0
04-13    75.0
04-14    67.0
04-15    43.0
04-16    43.0
04-17    43.0
04-18    67.0
04-19    41.0
04-20    41.0
04-21    43.0
04-22    43.0
04-23    43.0
04-24    43.0
04-25    43.0
04-26    43.0
04-27    50.0
04-28    43.0
04-29    43.0
04-30    43.0
05-01    43.0
05-02    41.0
05-03    43.0
05-04    58.0
05-05    43.0
05-06    43.0
05-07    41.0
05-08    43.0
05-09    43.0
05-10    43.0
05-11    58.0
         ...
09-21    67.0
09-22    32.0
09-23    38.0
09-24    43.0
09-25    43.0
09-26    32.0
09-27    41.0
09-28    67.0
09-29    32.0
09-30    38.0
10-01    43.0
10-02    43.0
10-03    32.0
10-04    41.0
10-05    58.0
10-06    32.0
10-07    41.0
10-08    43.0
10-09    43.0
10-10    32.0
10-11    41.0
10-12    58.0
10-13    32.0
10-14    41.0
10-15    43.0
10-16    43.0
10-17    32.0
10-18    41.0
10-19    58.0
10-20    32.0
Name: price, Length: 188, dtype: float64

In [405]:
x,y = M_to_B_Turista_price_min.index.tolist(),M_to_B_Turista_price_min.values.tolist()
line = (
    Line()
    .add_xaxis(x)
    .add_yaxis("票价", y,label_opts=opts.LabelOpts(is_show=False),
               markline_opts=opts.MarkLineOpts(data=[opts.MarkLineItem(type_="min")]),
              )

    .set_global_opts(title_opts=opts.TitleOpts(title=""), xaxis_opts=opts.AxisOpts(
            axistick_opts=opts.AxisTickOpts(is_align_with_label=False),
            axislabel_opts={"rotate":-90},
            is_scale=False,
            boundary_gap=False,
        ),)
)
line.render("全年最低票价.html")

'C:\\Users\\hali\\Desktop\\西班牙高铁数据\\全年最低票价.html'

In [390]:
price_min = M_to_B_Turista.loc[(M_to_B_Turista["price"]<=33)&(M_to_B_Turista["price"]>0)]
price_min

,origin,destination,start_date,end_date,train_type,price,train_class,fare,day,hour
801739,MADRID,BARCELONA,2019-07-20 19:30:00,2019-07-20 22:40:00,AVE,32.3,Turista,Promo,07-20,19:30:00
2026433,MADRID,BARCELONA,2019-08-06 06:20:00,2019-08-06 09:34:00,AVE,32.3,Turista,Promo,08-06,06:20:00
4460637,MADRID,BARCELONA,2019-10-20 06:20:00,2019-10-20 09:29:00,AVE,32.3,Turista,Promo,10-20,06:20:00
4460797,MADRID,BARCELONA,2019-10-13 06:20:00,2019-10-13 09:29:00,AVE,32.3,Turista,Promo,10-13,06:20:00
4460883,MADRID,BARCELONA,2019-10-10 05:50:00,2019-10-10 08:55:00,AVE,32.3,Turista,Promo,10-10,05:50:00
4460998,MADRID,BARCELONA,2019-10-06 06:20:00,2019-10-06 09:29:00,AVE,32.3,Turista,Promo,10-06,06:20:00
4461087,MADRID,BARCELONA,2019-10-03 05:50:00,2019-10-03 08:55:00,AVE,32.3,Turista,Promo,10-03,05:50:00
4461206,MADRID,BARCELONA,2019-09-29 06:20:00,2019-09-29 09:29:00,AVE,32.3,Turista,Promo,09-29,06:20:00
4461279,MADRID,BARCELONA,2019-09-26 05:50:00,2019-09-26 08:55:00,AVE,32.3,Turista,Promo,09-26,05:50:00
4461354,MADRID,BARCELONA,2019-09-22 06:20:00,2019-09-22 09:29:00,AVE,32.3,Turista,Promo,09-22,06:20:00
4461490,MADRID,BARCELONA,2019-09-19 05:50:00,2019-09-19 08:55:00,AVE,32.3,Turista,Promo,09-19,05:50:00
4470232,MADRID,BARCELONA,2019-10-17 05:50:00,2019-10-17 08:55:00,AVE,32.3,Turista,Promo,10-17,05:50:00
6049262,MADRID,BARCELONA,2019-07-04 05:50:00,2019-07-04 08:55:00,AVE,32.3,Turista,Promo,07-04,05:50:00
6049503,MADRID,BARCELONA,2019-06-24 14:30:00,2019-06-24 17:21:00,AVE,32.3,Turista,Promo,06-24,14:30:00
6049596,MADRID,BARCELONA,2019-06-20 05:50:00,2019-06-20 08:55:00,AVE,32.3,Turista,Promo,06-20,05:50:00
6049730,MADRID,BARCELONA,2019-06-17 14:30:00,2019-06-17 17:21:00,AVE,32.3,Turista,Promo,06-17,14:30:00
6049887,MADRID,BARCELONA,2019-06-10 14:30:00,2019-06-10 17:21:00,AVE,32.3,Turista,Promo,06-10,14:30:00
6049971,MADRID,BARCELONA,2019-06-06 05:50:00,2019-06-06 08:55:00,AVE,32.3,Turista,Promo,06-06,05:50:00
6054937,MADRID,BARCELONA,2019-06-27 05:50:00,2019-06-27 08:55:00,AVE,32.3,Turista,Promo,06-27,05:50:00
6055317,MADRID,BARCELONA,2019-06-13 05:50:00,2019-06-13 08:55:00,AVE,32.3,Turista,Promo,06-13,05:50:00
6055625,MADRID,BARCELONA,2019-06-03 14:30:00,2019-06-03 17:21:00,AVE,32.3,Turista,Promo,06-03,14:30:00
6125669,MADRID,BARCELONA,2019-07-06 19:30:00,2019-07-06 22:40:00,AVE,32.3,Turista,Promo,07-06,19:30:00
6125677,MADRID,BARCELONA,2019-07-06 06:20:00,2019-07-06 09:29:00,AVE,32.3,Turista,Promo,07-06,06:20:00
7148701,MADRID,BARCELONA,2019-07-18 05:50:00,2019-07-18 08:55:00,AVE,32.3,Turista,Promo,07-18,05:50:00

## 全年价格波动

In [368]:

from pyecharts import options as opts
from pyecharts.charts import Bar, Grid, Line,Scatter

from pyecharts import options as opts
from pyecharts.charts import Bar

x,y,z = checi.index.tolist(),checi.values.tolist(),M_to_B_Turista_price.values.tolist()

bar = (
    Bar()
    .add_xaxis(x)
    .add_yaxis("出行人数",y,  markpoint_opts=opts.MarkPointOpts(
                data=[opts.MarkPointItem(type_="max")]
            ),
              )                                                       
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    
    .set_global_opts(
        title_opts=opts.TitleOpts(title="出行人数"),
        xaxis_opts=opts.AxisOpts(
            axistick_opts=opts.AxisTickOpts(is_align_with_label=False),
            axislabel_opts={"rotate":-90},
            is_scale=False,
            boundary_gap=False,
        ),
        
    )
    .extend_axis(
        yaxis=opts.AxisOpts(
            name="票价",
            type_="value",
            min_=0,
           # max_=1.00,
            position="right",
            axisline_opts=opts.AxisLineOpts(
                linestyle_opts=opts.LineStyleOpts(color="#d14a61")
            ),
            axislabel_opts=opts.LabelOpts(formatter="{value}"),
        )
    )
 )
line = (
    Line()
    .add_xaxis(x)
    .add_yaxis("票价", z,yaxis_index=1,label_opts=opts.LabelOpts(is_show=False),
               markpoint_opts=opts.MarkPointOpts(
                   data=[opts.MarkPointItem(type_="max")]
               ),
              )

    .set_global_opts(title_opts=opts.TitleOpts(title=""),)
)
   


bar.overlap(line)
grid = (
        Grid()
        .add(bar, opts.GridOpts(pos_left="10%", pos_right="10%"), is_control_axis_index=True)
        
    )


grid.render("出行人数和票价波动.html")

'C:\\Users\\hali\\Desktop\\西班牙高铁数据\\出行人数和票价波动.html'

### 巴塞罗那到马德里的票价波动

In [369]:
B_to_M = train_price_wave_2019.loc[(train_price_wave_2019["origin"]=="BARCELONA")&(train_price_wave_2019["destination"]=="MADRID")]
B_to_M.shape

(19088, 10)

In [370]:
B_to_M_Turista = B_to_M.loc[B_to_M["train_class"]=="Turista"]
B_to_M_Turista_price = B_to_M_Turista.groupby("day")["price"].mean().round(0)
B_to_M_Turista_price

day
04-14    114.0
04-15     93.0
04-16     98.0
04-17     98.0
04-18    102.0
04-19     91.0
04-20     96.0
04-21    105.0
04-22     93.0
04-23     88.0
04-24     86.0
04-25     81.0
04-26     85.0
04-27     79.0
04-28     89.0
04-29     81.0
04-30     76.0
05-01     74.0
05-02     81.0
05-03     91.0
05-04     93.0
05-05    100.0
05-06     87.0
05-07     83.0
05-08     85.0
05-09     88.0
05-10     92.0
05-11     82.0
05-12     87.0
05-13     89.0
         ...
09-21     75.0
09-22     82.0
09-23     71.0
09-24     83.0
09-25     84.0
09-26     84.0
09-27     84.0
09-28     75.0
09-29     82.0
09-30     73.0
10-01     83.0
10-02     87.0
10-03     82.0
10-04     85.0
10-05     70.0
10-06     74.0
10-07     76.0
10-08     83.0
10-09     87.0
10-10     83.0
10-11     86.0
10-12     70.0
10-13     74.0
10-14     74.0
10-15     83.0
10-16     87.0
10-17     83.0
10-18     85.0
10-19     70.0
10-20     74.0
Name: price, Length: 190, dtype: float64

In [371]:

from pyecharts import options as opts
from pyecharts.charts import Bar, Grid, Line,Scatter

from pyecharts import options as opts
from pyecharts.charts import Bar

x,y,z = checi.index.tolist(),checi.values.tolist(),B_to_M_Turista_price.values.tolist()

bar = (
    Bar()
    .add_xaxis(x)
    .add_yaxis("出行人数",y,  markpoint_opts=opts.MarkPointOpts(
                data=[opts.MarkPointItem(type_="max")]
            ),
              )                                                       
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    
    .set_global_opts(
        title_opts=opts.TitleOpts(title="出行人数"),
        xaxis_opts=opts.AxisOpts(
            axistick_opts=opts.AxisTickOpts(is_align_with_label=False),
            axislabel_opts={"rotate":-90},
            is_scale=False,
            boundary_gap=False,
        ),
        
    )
    .extend_axis(
        yaxis=opts.AxisOpts(
            name="票价",
            type_="value",
            min_=0,
           # max_=1.00,
            position="right",
            axisline_opts=opts.AxisLineOpts(
                linestyle_opts=opts.LineStyleOpts(color="#d14a61")
            ),
            axislabel_opts=opts.LabelOpts(formatter="{value}"),
        )
    )
 )
line = (
    Line()
    .add_xaxis(x)
    .add_yaxis("票价", z,yaxis_index=1,label_opts=opts.LabelOpts(is_show=False),
               markpoint_opts=opts.MarkPointOpts(
                   data=[opts.MarkPointItem(type_="max")]
               ),
              )

    .set_global_opts(title_opts=opts.TitleOpts(title=""),)
)
   


bar.overlap(line)
grid = (
        Grid()
        .add(bar, opts.GridOpts(pos_left="10%", pos_right="10%"), is_control_axis_index=True)
        
    )


grid.render("B_M_出行人数和票价波动.html")

'C:\\Users\\hali\\Desktop\\西班牙高铁数据\\B_M_出行人数和票价波动.html'